version: '2'
services:
  neo4j:
    build: ./docker/db/neo4j/
    ports:
      - "7687:7687"
      - "7474:7474"
  redis:
    build: ./docker/db/redis/
    ports:
      - "6379:6379"
  python:
    build: .
    links:
      - neo4j
      - redis
    volumes:
      - ".:/aramazd/"
